# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\leejoonho\Desktop\joon_code\web_blog_crawling\test\textbrower\textbrowserTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 228)
        self.textbrow_Test = QtWidgets.QTextBrowser(Dialog)
        self.textbrow_Test.setGeometry(QtCore.QRect(10, 20, 256, 192))
        self.textbrow_Test.setObjectName("textbrow_Test")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(280, 50, 116, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_Print = QtWidgets.QPushButton(self.widget)
        self.btn_Print.setObjectName("btn_Print")
        self.verticalLayout.addWidget(self.btn_Print)
        self.btn_setText = QtWidgets.QPushButton(self.widget)
        self.btn_setText.setObjectName("btn_setText")
        self.verticalLayout.addWidget(self.btn_setText)
        self.btn_appendText = QtWidgets.QPushButton(self.widget)
        self.btn_appendText.setObjectName("btn_appendText")
        self.verticalLayout.addWidget(self.btn_appendText)
        self.btn_Clear = QtWidgets.QPushButton(self.widget)
        self.btn_Clear.setObjectName("btn_Clear")
        self.verticalLayout.addWidget(self.btn_Clear)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Print.setText(_translate("Dialog", "Print"))
        self.btn_setText.setText(_translate("Dialog", "SetText"))
        self.btn_appendText.setText(_translate("Dialog", "AppendText"))
        self.btn_Clear.setText(_translate("Dialog", "Clear"))
