# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\leejoonho\Desktop\joon_code\web_blog_crawling\test\combobox\comboboxTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 304)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 24, 371, 265))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_display = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_display.setObjectName("lbl_display")
        self.verticalLayout.addWidget(self.lbl_display)
        self.cmb_Test = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_Test.setObjectName("cmb_Test")
        self.cmb_Test.addItem("")
        self.cmb_Test.addItem("")
        self.cmb_Test.addItem("")
        self.verticalLayout.addWidget(self.cmb_Test)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_printItem = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_printItem.setObjectName("btn_printItem")
        self.horizontalLayout_2.addWidget(self.btn_printItem)
        self.btn_clearItem = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_clearItem.setObjectName("btn_clearItem")
        self.horizontalLayout_2.addWidget(self.btn_clearItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineedit_addItem = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineedit_addItem.setObjectName("lineedit_addItem")
        self.horizontalLayout.addWidget(self.lineedit_addItem)
        self.btn_addItem = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_addItem.setObjectName("btn_addItem")
        self.horizontalLayout.addWidget(self.btn_addItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cmb_second = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_second.setObjectName("cmb_second")
        self.horizontalLayout_3.addWidget(self.cmb_second)
        self.btn_deleteItem = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_deleteItem.setObjectName("btn_deleteItem")
        self.horizontalLayout_3.addWidget(self.btn_deleteItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_display.setText(_translate("Dialog", "Display ComboBox Text"))
        self.cmb_Test.setItemText(0, _translate("Dialog", "1st Item"))
        self.cmb_Test.setItemText(1, _translate("Dialog", "2nd Item"))
        self.cmb_Test.setItemText(2, _translate("Dialog", "3rd Item"))
        self.btn_printItem.setText(_translate("Dialog", "PrintItem"))
        self.btn_clearItem.setText(_translate("Dialog", "ClearItem"))
        self.label.setText(_translate("Dialog", "Add Item to ComboBox"))
        self.btn_addItem.setText(_translate("Dialog", "AddItem"))
        self.label_2.setText(_translate("Dialog", "Delete ComboBox Item"))
        self.btn_deleteItem.setText(_translate("Dialog", "DeleteItem"))
