# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\leejoonho\Desktop\joon_code\web_blog_crawling\qtprogram\blog_macro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_myCalculator(object):
    def setupUi(self, myCalculator):
        myCalculator.setObjectName("myCalculator")
        myCalculator.resize(311, 412)
        myCalculator.setStyleSheet("background-color: black")
        self.btn_start = QtWidgets.QPushButton(myCalculator)
        self.btn_start.setGeometry(QtCore.QRect(20, 340, 201, 61))
        self.btn_start.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_start.setObjectName("btn_start")
        self.display_content = QtWidgets.QTextBrowser(myCalculator)
        self.display_content.setGeometry(QtCore.QRect(20, 20, 271, 251))
        self.display_content.setAutoFillBackground(False)
        self.display_content.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 87 24pt \"Montserrat\";\n"
"")
        self.display_content.setObjectName("display_content")
        self.btn_del = QtWidgets.QPushButton(myCalculator)
        self.btn_del.setGeometry(QtCore.QRect(230, 340, 61, 61))
        self.btn_del.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 200 24pt \"Montserrat\";")
        self.btn_del.setObjectName("btn_del")
        self.spinBox_count = QtWidgets.QSpinBox(myCalculator)
        self.spinBox_count.setGeometry(QtCore.QRect(190, 290, 101, 31))
        self.spinBox_count.setObjectName("spinBox_count")
        self.comboBox = QtWidgets.QComboBox(myCalculator)
        self.comboBox.setGeometry(QtCore.QRect(20, 290, 151, 21))
        self.comboBox.setStyleSheet("background-color:rgb(25,25,25);\n"
"color: white;\n"
"border-radius: 8px;\n"
"font: 60 24pt \"Montserrat\";\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(myCalculator)
        QtCore.QMetaObject.connectSlotsByName(myCalculator)

    def retranslateUi(self, myCalculator):
        _translate = QtCore.QCoreApplication.translate
        myCalculator.setWindowTitle(_translate("myCalculator", "myCalculator"))
        self.btn_start.setText(_translate("myCalculator", "시작"))
        self.display_content.setHtml(_translate("myCalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Montserrat\'; font-size:24pt; font-weight:80; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">contents</span></p></body></html>"))
        self.btn_del.setText(_translate("myCalculator", "Del"))
        self.comboBox.setItemText(0, _translate("myCalculator", "blender"))
        self.comboBox.setItemText(1, _translate("myCalculator", "python"))
        self.comboBox.setItemText(2, _translate("myCalculator", "센텀준호"))
